title: "좀 더 빠 르 게"
description: "p o c o m o s s o"
about: "p o c o m o s s o"
location: "Incheon, South Korea"
email: 2pocomosso@gmail.com
baseurl: ""
url: "http://pocomosso.github.io"
twitter_username: 
github_username:  pocomosso
author: "monthly pocomosso"

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: Kr
close_btn: "Ausblenden"
home_btn: "Startseite"
projects_btn: "Projekte"
posts_btn: "Posts"
imprint_btn: "Impressum"
name_badge: "Ein Artikel von"
rss_badge: "Feed abbonieren!"

# build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    tab_width: 4
    
# third party gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

whitelist:
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  
# exclude files
exclude:
  - LICENSE
  - README.md
